name: travel_match_app
description: "Tinder-style travel matching app"
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_card_swiper: ^7.0.2
  cupertino_icons: ^1.0.2
  logging: ^1.2.0
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/swipe_icon.png
    - assets/swipe_logo.png
    - assets/places/
